#!/usr/bin/python

from __future__ import print_function

import sys
import consts as Consts
from Board import Board
import tk_draw

DEBUG = False


def main(args):
    ''' Initialize game '''
    if DEBUG:
        print('creating Board ...')
    board = Board()
    if DEBUG:
        print('... board created')
        print('initial field : ')
        print(board.field)
    instance = tk_draw.get_instance()
    window = tk_draw.get_window(instance, board)
    tk_draw.draw_board(window, board)
    tk_draw.attachUpdater(instance, window, board)
    tk_draw.attachMainloop(instance)
    if DEBUG:
        print('out')

if __name__ == '__main__':
    ''' Entry point '''
    if len(sys.argv) in (1, 2):
        main(sys.argv[1:])
    else:
        print(Consts.USAGE)
